plugins {
    id 'net.fabricmc.fabric-loom' version '1.7-SNAPSHOT'
    id 'maven-publish'
}

version = "1.0.0"
group = "com.example.guiscale"

repositories {
    maven { url "https://maven.fabricmc.net/" }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.1"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:0.16.0"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.102.0+1.21.1"
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}
